// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/admin" | "/admin/dashboard" | "/ai-gateway" | "/api-keys" | "/auth/auth-code-error" | "/billing" | "/blog" | "/blog/apache-bench-performance-report" | "/blog/building-ai-agents" | "/blog/future-of-llm" | "/blog/gdpr-and-data-residency" | "/blog/multi-tenant-ai-architecture" | "/blog/pii-redaction-at-the-edge" | "/blog/rbac-in-ai-gateways" | "/blog/semantic-caching-deep-dive" | "/blog/soc2-compliance-guide" | "/blog/top-5-ai-gateways-2026" | "/blog/webhook-driven-ai-workflows" | "/blog/whats-frenix" | "/blog/why-frenix" | "/careers" | "/community" | "/compare/openrouter-alternative" | "/dashboard" | "/dashboard/webhooks" | "/demo" | "/demo-dropdown" | "/docs" | "/integrations/anthropic" | "/integrations/openai" | "/llm-gateway" | "/models" | "/oauth/consent" | "/openai-compatible-api" | "/owner" | "/playground" | "/privacy" | "/refund" | "/signin" | "/status" | "/team" | "/team/dashboard" | "/terms" | "/test-oauth" | "/test-oauth/callback" | "/test-real-oauth" | "/use-cases/agents" | "/use-cases/startups"
type AppRouteHandlerRoutes = "/api/gateway/keys" | "/api/gateway/stats" | "/api/gateway/status" | "/api/oauth/apps" | "/api/oauth/apps/[id]" | "/api/oauth/decision" | "/api/oauth/token" | "/api/oauth/user" | "/auth/callback" | "/oauth/authorize"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/admin": {}
  "/admin/dashboard": {}
  "/ai-gateway": {}
  "/api-keys": {}
  "/api/gateway/keys": {}
  "/api/gateway/stats": {}
  "/api/gateway/status": {}
  "/api/oauth/apps": {}
  "/api/oauth/apps/[id]": { "id": string; }
  "/api/oauth/decision": {}
  "/api/oauth/token": {}
  "/api/oauth/user": {}
  "/auth/auth-code-error": {}
  "/auth/callback": {}
  "/billing": {}
  "/blog": {}
  "/blog/apache-bench-performance-report": {}
  "/blog/building-ai-agents": {}
  "/blog/future-of-llm": {}
  "/blog/gdpr-and-data-residency": {}
  "/blog/multi-tenant-ai-architecture": {}
  "/blog/pii-redaction-at-the-edge": {}
  "/blog/rbac-in-ai-gateways": {}
  "/blog/semantic-caching-deep-dive": {}
  "/blog/soc2-compliance-guide": {}
  "/blog/top-5-ai-gateways-2026": {}
  "/blog/webhook-driven-ai-workflows": {}
  "/blog/whats-frenix": {}
  "/blog/why-frenix": {}
  "/careers": {}
  "/community": {}
  "/compare/openrouter-alternative": {}
  "/dashboard": {}
  "/dashboard/webhooks": {}
  "/demo": {}
  "/demo-dropdown": {}
  "/docs": {}
  "/integrations/anthropic": {}
  "/integrations/openai": {}
  "/llm-gateway": {}
  "/models": {}
  "/oauth/authorize": {}
  "/oauth/consent": {}
  "/openai-compatible-api": {}
  "/owner": {}
  "/playground": {}
  "/privacy": {}
  "/refund": {}
  "/signin": {}
  "/status": {}
  "/team": {}
  "/team/dashboard": {}
  "/terms": {}
  "/test-oauth": {}
  "/test-oauth/callback": {}
  "/test-real-oauth": {}
  "/use-cases/agents": {}
  "/use-cases/startups": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
