// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/ai-gateway/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-gateway">> = Specific
  const handler = {} as typeof import("../../../src/app/ai-gateway/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-keys">> = Specific
  const handler = {} as typeof import("../../../src/app/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/auth-code-error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/auth-code-error">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/auth-code-error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../../src/app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/apache-bench-performance-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/apache-bench-performance-report">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/apache-bench-performance-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/building-ai-agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/building-ai-agents">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/building-ai-agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/future-of-llm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/future-of-llm">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/future-of-llm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/gdpr-and-data-residency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/gdpr-and-data-residency">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/gdpr-and-data-residency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/multi-tenant-ai-architecture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/multi-tenant-ai-architecture">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/multi-tenant-ai-architecture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/pii-redaction-at-the-edge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/pii-redaction-at-the-edge">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/pii-redaction-at-the-edge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/rbac-in-ai-gateways/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/rbac-in-ai-gateways">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/rbac-in-ai-gateways/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/semantic-caching-deep-dive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/semantic-caching-deep-dive">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/semantic-caching-deep-dive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/soc2-compliance-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/soc2-compliance-guide">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/soc2-compliance-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/top-5-ai-gateways-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/top-5-ai-gateways-2026">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/top-5-ai-gateways-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/webhook-driven-ai-workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/webhook-driven-ai-workflows">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/webhook-driven-ai-workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/whats-frenix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/whats-frenix">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/whats-frenix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/why-frenix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/why-frenix">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/why-frenix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../../src/app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community">> = Specific
  const handler = {} as typeof import("../../../src/app/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/compare/openrouter-alternative/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare/openrouter-alternative">> = Specific
  const handler = {} as typeof import("../../../src/app/compare/openrouter-alternative/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/webhooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/webhooks">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/webhooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/demo-dropdown/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo-dropdown">> = Specific
  const handler = {} as typeof import("../../../src/app/demo-dropdown/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../../src/app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../../src/app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/integrations/anthropic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations/anthropic">> = Specific
  const handler = {} as typeof import("../../../src/app/integrations/anthropic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/integrations/openai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integrations/openai">> = Specific
  const handler = {} as typeof import("../../../src/app/integrations/openai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/llm-gateway/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/llm-gateway">> = Specific
  const handler = {} as typeof import("../../../src/app/llm-gateway/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/models/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/models">> = Specific
  const handler = {} as typeof import("../../../src/app/models/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/oauth/consent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/oauth/consent">> = Specific
  const handler = {} as typeof import("../../../src/app/oauth/consent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/openai-compatible-api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/openai-compatible-api">> = Specific
  const handler = {} as typeof import("../../../src/app/openai-compatible-api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/owner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner">> = Specific
  const handler = {} as typeof import("../../../src/app/owner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/playground/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playground">> = Specific
  const handler = {} as typeof import("../../../src/app/playground/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/refund/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refund">> = Specific
  const handler = {} as typeof import("../../../src/app/refund/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../../src/app/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/status">> = Specific
  const handler = {} as typeof import("../../../src/app/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/team/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/team/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../../src/app/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-oauth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-oauth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/test-oauth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-oauth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-oauth">> = Specific
  const handler = {} as typeof import("../../../src/app/test-oauth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-real-oauth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-real-oauth">> = Specific
  const handler = {} as typeof import("../../../src/app/test-real-oauth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/use-cases/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/use-cases/agents">> = Specific
  const handler = {} as typeof import("../../../src/app/use-cases/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/use-cases/startups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/use-cases/startups">> = Specific
  const handler = {} as typeof import("../../../src/app/use-cases/startups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/gateway/keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gateway/keys">> = Specific
  const handler = {} as typeof import("../../../src/app/api/gateway/keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/gateway/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gateway/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/gateway/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/gateway/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gateway/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/gateway/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/oauth/apps/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/apps/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/oauth/apps/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/oauth/apps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/apps">> = Specific
  const handler = {} as typeof import("../../../src/app/api/oauth/apps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/oauth/decision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/decision">> = Specific
  const handler = {} as typeof import("../../../src/app/api/oauth/decision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/oauth/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/token">> = Specific
  const handler = {} as typeof import("../../../src/app/api/oauth/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/oauth/user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/user">> = Specific
  const handler = {} as typeof import("../../../src/app/api/oauth/user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/oauth/authorize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/oauth/authorize">> = Specific
  const handler = {} as typeof import("../../../src/app/oauth/authorize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
